name: build

on: 
#  push:
#    branches:
#    - "*"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [MI-R4A, NETGEAR-BZV]
    steps:
      - uses: actions/checkout@v4
      - uses: hendrikmuhs/ccache-action@v1.2
        with: 
            key: ${{ matrix.target }}
      - uses: actions/setup-go@v5
        with:
            go-version: '1.22'
            check-latest: true
            cache: false
      - uses: actions/setup-node@v4
        with:
            node-version: 20
            check-latest: true 
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Start Build
        run: |
          make ${{ matrix.target }}
          echo "TAG_ANME=$(TZ='Asia/Shanghai' date +%Y.%m.%d-%H%M)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ env.TAG_ANME }}
          path: trunk/images/*.trx
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: trunk/images/*.trx
          allowUpdates: true
